project:
  type: book
  output-dir: docs

book:
  title: "Glossar des Projekts"
  subtitle: " Co-Kreation in der Region – Systemisch und innovativ Transfer entwickeln (Co-Site)"
  author: ""
  date: "2024-10-17"
  chapters:
    - index.qmd
    - cosite001.ipynb
    - cosite002.ipynb
    # - ipcc-wip.ipynb
    # - epa.ipynb
    # - resources/cct.qmd
    # - glossaries.qmd
    - imprint.qmd
    - contributors.qmd 
    - references.qmd
  repo-url: https://github.com/TIBHannover/co-site-glossar
  repo-actions: [edit]
  downloads: [pdf,docx,epub]
  cover-image: cover/thkoeln_cover.png 
  page-footer: 
    center: "[NextGen Books / CPS](https://projects.tib.eu/nextgen-books/)"
    right: "[Impressum](https://projects.tib.eu/nextgen-books/impressum/)"  
    left: "[Datenschutz](https://projects.tib.eu/nextgen-books/datenschutz/)" 

comments:
  hypothesis: true

#filters: 
#  - "filters/phantom-section.lua"

bibliography: references.bib

format:
  html:
    number-sections: false
    theme: 'lux'
    css: 'thkoelnepub.css'
    lang: de

  pdf:
    #latex-engine: xelatex
    lang: de
    number-sections: false
    toc-depth: 3
    documentclass: book
    include-in-header: "in-header.tex"
    pagestyle: plain # page numbers
    geometry: # margins
      - top=35mm
      - right=25mm
      - bottom=35mm
      - left=25mm
      - heightrounded
    classoption: openany 
    fontsize: 12pt
    papersize: a4
    template-partials:
      - "_titlepage.tex" 
      - "before-body.tex"
    title-bg-image: "cover/thkoeln_cover.png"
    title-bg-location: "LR" # UL, UR, LR, LL, leave empty for centered
    title-bg-size: 0.30
    title-boxcolor: gray!15!black
    title-boxopacity: 0
    title-boxfontcolor: black
    pdfborderstyle: {/S/U/W 1}
    #colorlinks: false
    #urlcolor: black
    #linkcolor: black
    #filecolor: black
    #keep-tex: true 
  
  docx: 
    toc: true
    reference-doc: "thkoeln_template.docx"
    number-sections: false
    toc-depth: 3

  epub:
    toc: true 
    toc-depth: 3
    number-sections: false
    css: "thkoelnepub.css"
    code-overflow: wrap
    epub-fonts: ['./fonts/MyriadPro-*.otf']