# Literatur {.unnumbered}

:::{.paragraph-spaces}

## Grüne Infrastruktur

Frantzeskaki, Niki. 2019. „Seven lessons for planning nature-based solutions in cities”. *Environmental Science & Policy*, 93, 101–111. [https://doi.org/10.1016/j.envsci.2018.12.033](https://doi.org/10.1016/j.envsci.2018.12.033).

Deutscher Wetterdienst. o. J. „Klimawirkung – Deutscher Wetterdienst”. [https://www.dwd.de/DE/forschung/klima_umwelt/klimawirk/klimawirk_node.html](https://www.dwd.de/DE/forschung/klima_umwelt/klimawirk/klimawirk_node.html).

Naturkapital Deutschland − TEEB DE. o. J. „Glossar – Naturkapital Deutschland – TEEB DE”. [https://www.ufz.de/teebde/index.php?de=43784](https://www.ufz.de/teebde/index.php?de=43784).

## KRITIS

Bundesamt für Bevölkerungsschutz und Katastrophenhilfe. o. J. „Sektoren und Branchen KRITIS”. [https://www.bbk.bund.de/DE/Themen/Kritische-Infrastrukturen/Sektoren-Branchen/sektoren-branchen_node.html](https://www.bbk.bund.de/DE/Themen/Kritische-Infrastrukturen/Sektoren-Branchen/sektoren-branchen_node.html).

Bundesamt für Bevölkerungsschutz und Katastrophenhilfe. o. J. „Glossar des Bundesamts für Bevölkerungsschutz und Katastrophenhilfe”. [https://www.bbk.bund.de/DE/Infothek/Glossar/glossar_node.html](https://www.bbk.bund.de/DE/Infothek/Glossar/glossar_node.html).

Bundesamt für Sicherheit in der Informationstechnik. 2024. „Flyer UP KRITIS”. [https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/KRITIS/UPK/upk-flyer.html](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/KRITIS/UPK/upk-flyer.html).

Bundesministerium des Innern und für Heimat. 2009. „Nationale Strategie zum Schutz Kritischer Infrastrukturen (KRITIS-Strategie)”. [https://www.bmi.bund.de/SharedDocs/downloads/DE/publikationen/themen/bevoelkerungsschutz/kritis.html](https://www.bmi.bund.de/SharedDocs/downloads/DE/publikationen/themen/bevoelkerungsschutz/kritis.html).

CIPRNet. o. J. „CIPedia”. [https://websites.fraunhofer.de/CIPedia/index.php/CIPedia%C2%A9_Main_Page](https://websites.fraunhofer.de/CIPedia/index.php/CIPedia%C2%A9_Main_Page).

IPCC. o. J. „IPCC Glossary”. [https://apps.ipcc.ch/glossary/](https://apps.ipcc.ch/glossary/).

Käpplinger, Bernd. 2023. „Betriebliche Weiterbildung – Digitales Wörterbuch Erwachsenen- und Weiterbildung”. In *Digitales Wörterbuch Erwachsenen- und Weiterbildung*. [https://doi.org/10.35468/wbeb2022-030](https://doi.org/10.35468/wbeb2022-030).

NIST. 2019. „Glossary of Key Information Security Terms”. [https://csrc.nist.gov/glossary](https://csrc.nist.gov/glossary).

Rinaldi, S. M.; Peerenboom, J. P.; Kelly, T. K. 2001. „Identifying, understanding, and analyzing critical infrastructure interdependencies”. *IEEE Control Systems Magazine*, 21(6), 11–25. [https://doi.org/10.1109/37.969131](https://doi.org/10.1109/37.969131).

Arnold, Rolf. 2023b. „Qualifikation – Digitales Wörterbuch Erwachsenen- und Weiterbildung”. In *Digitales Wörterbuch Erwachsenen- und Weiterbildung*. [https://doi.org/10.35468/wbeb2022-237](https://doi.org/10.35468/wbeb2022-237).

BMI, Referat SW I 1 – Stadtentwicklungspolitik; Weigel, Oliver. 2021. „Memorandum „Urbane Resilienz – Wege zur robusten, adaptiven und zukunftsfähigen Stadt””. Bundesministerium des Innern, für Bau und Heimat. [https://www.nationale-stadtentwicklungspolitik.de/NSPWeb/SharedDocs/Publikationen/DE/Publikationen/memorandum_urbane_resilienz.pdf](https://www.nationale-stadtentwicklungspolitik.de/NSPWeb/SharedDocs/Publikationen/DE/Publikationen/memorandum_urbane_resilienz.pdf).

## Nachhaltigkeit

Bundesregierung. 2023. „Ein Kompass für die Zukunft – Die Deutsche Nachhaltigkeitsstrategie”. [https://www.bundesregierung.de/breg-de/schwerpunkte-der-bundesregierung/nachhaltigkeitspolitik/deutsche-nachhaltigkeitsstrategie-318846](https://www.bundesregierung.de/breg-de/schwerpunkte-der-bundesregierung/nachhaltigkeitspolitik/deutsche-nachhaltigkeitsstrategie-318846).

Bundesministerium für Bildung und Forschung. 2024. „Was ist BNE?” [https://www.bne-portal.de/bne/de/einstieg/was-ist-bne/was-ist-bne.html](https://www.bne-portal.de/bne/de/einstieg/was-ist-bne/was-ist-bne.html).

## Responsivität

Metten, Thomas; Bornheim, Felix. 2021. „Responsive Wissenschaftskommunikation: Ein Realexperiment zur Bürgerbeteiligung in der Wissenschaftskommunikation”. Stabsabteilung für Bildungsinnovation und Wissenstransfer. [https://doi.org/10.17904/KU.EDOC.25950](https://doi.org/10.17904/KU.EDOC.25950).

## Risikomanagement

DIN Media GmbH. 2021. „Anpassung an den Klimawandel – Vulnerabilität, Auswirkungen und Risikobewertung (DIN EN ISO 14091)”. [https://doi.org/10.31030/3215272](https://doi.org/10.31030/3215272).

UNDRR. 2023. „Sendai Framework Terminology on Disaster Risk Reduction”. [http://www.undrr.org/drr-glossary/terminology](http://www.undrr.org/drr-glossary/terminology).

Zivilschutz- und Katastrophenhilfegesetz (ZSKG). 1997. „Zivilschutz- und Katastrophenhilfegesetz (ZSKG)”. [https://www.gesetze-im-internet.de/zsg/](https://www.gesetze-im-internet.de/zsg/).

## Weiterbildung

Arnold, Rolf. 2023a. „Fortbildung – Digitales Wörterbuch Erwachsenen- und Weiterbildung”. In *Digitales Wörterbuch Erwachsenen- und Weiterbildung*. [https://doi.org/10.35468/wbeb2022-109](https://doi.org/10.35468/wbeb2022-109).

Bendel, Prof. Dr. Oliver. 2024. „Definition: VUCA”. *Gabler Wirtschaftslexikon*. [https://wirtschaftslexikon.gabler.de/definition/vuca-119684](https://wirtschaftslexikon.gabler.de/definition/vuca-119684).

Dobischat, Rolf. 2023. „Berufliche Weiterbildung – Digitales Wörterbuch Erwachsenen- und Weiterbildung”. In *Digitales Wörterbuch Erwachsenen- und Weiterbildung*. [https://doi.org/10.35468/wbeb2022-028](https://doi.org/10.35468/wbeb2022-028).

Rohs, Matthias. 2023. „Wissenschaftliche Weiterbildung – Digitales Wörterbuch Erwachsenen- und Weiterbildung”. In *Digitales Wörterbuch Erwachsenen- und Weiterbildung*. [https://doi.org/10.35468/wbeb2022-299](https://doi.org/10.35468/wbeb2022-299).

## Wirkung

Hager, Willi; Patry, Jean-Luc; Brezing, Hermann (Hrsg.). 2000. „Evaluation psychologischer Interventionsmaßnahmen. Standards und Kriterien: Ein Handbuch.” Bern: Huber. ISBN 978-3-456-83245-6.

## Wissenschaftskommunikation

Dernbach, Beatrice; Kleinert, Christian; Münder, Herbert. 2012. „Einleitung: Die drei Ebenen der Wissenschaftskommunikation”. In *Handbuch Wissenschaftskommunikation*, 1–15. VS Verlag für Sozialwissenschaften. [https://doi.org/10.1007/978-3-531-18927-7_1](https://doi.org/10.1007/978-3-531-18927-7_1).

:::